package infoblox

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"time"

	"github.com/AbsaOSS/external-dns-infoblox-webhook/internal/metrics"
	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	log "github.com/sirupsen/logrus"
)

const (
	// defaultGetAttempts is the total number of attempts (initial call included)
	// made for a GET that fails transiently. Only transient failures are
	// retried; authentication and authorization failures fail immediately.
	defaultGetAttempts = 3
	// defaultGetRetryBackoff is the wait before the second attempt. It is
	// doubled for each further attempt.
	defaultGetRetryBackoff = 500 * time.Millisecond
)

// retrySleep is a seam so tests do not have to wait for the real backoff.
var retrySleep = time.Sleep

// getObjectWithRetry performs a single WAPI GET, retrying only transient
// failures (503, 504, 429, timeouts, EOF) up to attempts times. Authentication
// and authorization failures (401, 403) are returned on the first attempt so
// that a misconfigured WAPI user surfaces immediately instead of being retried
// indefinitely. Every failure is logged with its HTTP status code, the WAPI
// object type and the sanitized reason.
func getObjectWithRetry(
	c ibclient.IBConnector,
	obj ibclient.IBObject,
	ref string,
	queryParams *ibclient.QueryParams,
	res interface{},
	attempts int,
) error {
	if attempts < 1 {
		attempts = 1
	}
	objectType := obj.ObjectType()
	backoff := defaultGetRetryBackoff

	var err error
	for attempt := 1; attempt <= attempts; attempt++ {
		err = c.GetObject(obj, ref, queryParams, res)
		metrics.TotalApiCalls.Inc()
		if err == nil {
			return nil
		}

		failure := ClassifyWAPIError(err)
		logWAPIFailure(objectType, "GetObject", failure, attempt, attempts, err)
		if failure.Kind != WAPIFailureNotFound {
			metrics.FailedApiCallsTotal.Inc()
		}
		if !failure.Retryable() || attempt == attempts {
			return err
		}
		retrySleep(backoff)
		backoff *= 2
	}
	return err
}

func PagingGetObject[T any](
	c ibclient.IBConnector,
	obj ibclient.IBObject,
	ref string,
	queryParams map[string]string,
	res *[]T,
) (err error) {

	pagingResponse := pagingResponseStruct[T]{
		NextPageId: "",
		Result:     make([]T, 0),
	}

	//copy query params and update them
	queryParamsCopy := map[string]string{}
	for k, v := range queryParams {
		queryParamsCopy[k] = v
	}

	queryParamsCopy["_return_as_object"] = "1"
	queryParamsCopy["_paging"] = "1"
	queryParamsCopy["_max_results"] = "1000"

	err = getObjectWithRetry(c, obj, "", ibclient.NewQueryParams(false, queryParamsCopy), &pagingResponse, defaultGetAttempts)
	if err != nil {
		return fmt.Errorf("could not fetch %s objects: %w", obj.ObjectType(), err)
	}
	*res = append(*res, pagingResponse.Result...)

	for {
		if pagingResponse.NextPageId == "" {
			return
		}
		queryParamsCopy["_page_id"] = pagingResponse.NextPageId
		pagingResponse.NextPageId = ""
		pagingResponse.Result = make([]T, 0)
		err = getObjectWithRetry(c, obj, "", ibclient.NewQueryParams(false, queryParamsCopy), &pagingResponse, defaultGetAttempts)
		if err != nil {
			return fmt.Errorf("could not fetch %s objects: %w", obj.ObjectType(), err)
		}

		*res = append(*res, pagingResponse.Result...)
		log.WithFields(log.Fields{
			"wapi_object": obj.ObjectType(),
			"fetched":     len(*res),
		}).Debug("Paging to retrieve further Infoblox objects")
	}
}

type pagingResponseStruct[T any] struct {
	NextPageId string `json:"next_page_id,omitempty"`
	Result     []T    `json:"result,omitempty"`
}
