package infoblox

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	log "github.com/sirupsen/logrus"
	logtest "github.com/sirupsen/logrus/hooks/test"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/plan"
	"sigs.k8s.io/external-dns/provider"
)

const (
	testWAPIUser     = "wapi-user"
	testWAPIPassword = "sup3r-s3cret-p4ssw0rd"
)

// newStubGrid starts an HTTP server that answers every WAPI request with the
// given status code and body, and returns a Provider wired to a real
// infoblox-go-client connector pointed at it. The returned counter records how
// many HTTP requests the stub received, which is what pins the retry behaviour.
func newStubGrid(t *testing.T, status int, body string) (*Provider, *int64) {
	t.Helper()

	var requests int64
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		atomic.AddInt64(&requests, 1)
		w.WriteHeader(status)
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(srv.Close)

	stubURL, err := url.Parse(srv.URL)
	require.NoError(t, err)

	hostCfg := ibclient.HostConfig{
		Scheme:  "http",
		Host:    stubURL.Hostname(),
		Port:    stubURL.Port(),
		Version: "2.3.1",
	}
	authCfg := ibclient.AuthConfig{Username: testWAPIUser, Password: testWAPIPassword}
	requestBuilder, err := ibclient.NewWapiRequestBuilder(hostCfg, authCfg)
	require.NoError(t, err)
	client, err := ibclient.NewConnector(hostCfg, authCfg,
		ibclient.NewTransportConfig("false", 5, 2), requestBuilder, NewAuthAwareRequestor(&ibclient.WapiHttpRequestor{}))
	require.NoError(t, err)

	return &Provider{
		client:       client,
		domainFilter: endpoint.NewDomainFilter([]string{"example.com"}),
		config:       &StartupConfig{View: "default", Username: testWAPIUser, Password: testWAPIPassword},
	}, &requests
}

// captureLogs installs a logrus test hook at debug level and returns it.
func captureLogs(t *testing.T) *logtest.Hook {
	t.Helper()
	previousLevel := log.GetLevel()
	log.SetLevel(log.DebugLevel)
	hook := logtest.NewGlobal()
	t.Cleanup(func() {
		hook.Reset()
		log.SetLevel(previousLevel)
	})
	return hook
}

// withInstantRetries removes the retry backoff so a retry test does not sleep.
func withInstantRetries(t *testing.T) {
	t.Helper()
	previous := retrySleep
	retrySleep = func(time.Duration) {}
	t.Cleanup(func() { retrySleep = previous })
}

// assertNoSecretsLogged fails the test if any captured log entry, in message or
// in any field value, contains the WAPI password or a basic-auth header.
func assertNoSecretsLogged(t *testing.T, hook *logtest.Hook) {
	t.Helper()
	for _, entry := range hook.AllEntries() {
		haystack := entry.Message
		for _, v := range entry.Data {
			haystack += fmt.Sprintf(" %v", v)
		}
		assert.NotContains(t, haystack, testWAPIPassword, "log entry leaked the WAPI password")
		assert.NotContains(t, strings.ToLower(haystack), "authorization:", "log entry leaked an Authorization header")
		assert.NotContains(t, strings.ToLower(haystack), "basic ", "log entry leaked basic auth credentials")
	}
}

func TestClassifyWAPIError(t *testing.T) {
	cases := []struct {
		name           string
		err            error
		expectedKind   WAPIFailureKind
		expectedStatus int
		retryable      bool
	}{
		{
			name:           "401 unauthorized is an auth failure",
			err:            errors.New("WAPI request error: 401('401 Unauthorized')\nContents:\n\n"),
			expectedKind:   WAPIFailureAuth,
			expectedStatus: http.StatusUnauthorized,
		},
		{
			name:           "403 forbidden is an auth failure",
			err:            errors.New("WAPI request error: 403('403 Forbidden')\nContents:\nAdmiss...\n"),
			expectedKind:   WAPIFailureAuth,
			expectedStatus: http.StatusForbidden,
		},
		{
			name:           "503 is transient and retryable",
			err:            errors.New("WAPI request error: 503('503 Service Temporarily Unavailable')\nContents:\n\n"),
			expectedKind:   WAPIFailureTransient,
			expectedStatus: http.StatusServiceUnavailable,
			retryable:      true,
		},
		{
			name:           "504 is transient and retryable",
			err:            errors.New("WAPI request error: 504('504 Gateway Timeout')"),
			expectedKind:   WAPIFailureTransient,
			expectedStatus: http.StatusGatewayTimeout,
			retryable:      true,
		},
		{
			name:           "wrapped NotFoundError stays not found",
			err:            fmt.Errorf("could not fetch object: %w", ibclient.NewNotFoundError("nope")),
			expectedKind:   WAPIFailureNotFound,
			expectedStatus: http.StatusNotFound,
		},
		{
			name:         "bare EOF from the grid master is transient",
			err:          errors.New(`Get "https://grid/wapi/v2.3.1/record:host?_proxy_search=GM": EOF`),
			expectedKind: WAPIFailureTransient,
			retryable:    true,
		},
		{
			name:         "client timeout is transient",
			err:          errors.New(`Get "https://grid/wapi/v2.3.1/record:a": context deadline exceeded`),
			expectedKind: WAPIFailureTransient,
			retryable:    true,
		},
		{
			name:           "400 bad request is neither auth nor transient",
			err:            errors.New("WAPI request error: 400('400 Bad Request')"),
			expectedKind:   WAPIFailureOther,
			expectedStatus: http.StatusBadRequest,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			failure := ClassifyWAPIError(tc.err)
			assert.Equal(t, tc.expectedKind, failure.Kind)
			assert.Equal(t, tc.expectedStatus, failure.StatusCode)
			assert.Equal(t, tc.retryable, failure.Retryable())
		})
	}
}

func TestSanitizeWAPIReasonStripsCredentialsAndCollapsesLines(t *testing.T) {
	err := fmt.Errorf(`Get "https://%s:%s@grid.example.com/wapi/v2.3.1/record:a": WAPI request error: 401('401 Unauthorized')
Contents:
denied
`, testWAPIUser, testWAPIPassword)

	reason := SanitizeWAPIReason(err)

	assert.NotContains(t, reason, testWAPIPassword)
	assert.NotContains(t, reason, testWAPIUser)
	assert.NotContains(t, reason, "\n")
	assert.Contains(t, reason, "401")
}

func TestSanitizeWAPIReasonBoundsLength(t *testing.T) {
	reason := SanitizeWAPIReason(errors.New(strings.Repeat("x", reasonMaxLen*3)))
	assert.LessOrEqual(t, len(reason), reasonMaxLen+3)
}

// TestRecordsLogsAuthFailureWithoutRetry pins the fix for issue #50: a WAPI user
// that is rejected with 401 must produce an error-level log line naming the
// status code and the object type, and the call must not be retried.
func TestRecordsLogsAuthFailureWithoutRetry(t *testing.T) {
	hook := captureLogs(t)
	p, requests := newStubGrid(t, http.StatusUnauthorized, "401 Unauthorized")

	_, err := p.Records(context.TODO())
	require.Error(t, err)

	entry := findEntry(hook, log.ErrorLevel, WAPIFailureAuth)
	require.NotNil(t, entry, "expected an error-level log entry classified as an auth failure, got: %s", dumpEntries(hook))
	assert.Equal(t, http.StatusUnauthorized, entry.Data["http_status"])
	assert.Equal(t, "zone_auth", entry.Data["wapi_object"])
	assert.Contains(t, entry.Message, "INFOBLOX_WAPI_USER")

	assert.Equal(t, int64(1), *requests, "auth failures must not be retried")
	assertNoSecretsLogged(t, hook)
}

// TestRecordsLogsForbiddenFailure covers the read-only WAPI user from issue #50,
// which the grid answers with 403 rather than 401.
func TestRecordsLogsForbiddenFailure(t *testing.T) {
	hook := captureLogs(t)
	p, requests := newStubGrid(t, http.StatusForbidden, "403 Forbidden")

	_, err := p.Records(context.TODO())
	require.Error(t, err)

	entry := findEntry(hook, log.ErrorLevel, WAPIFailureAuth)
	require.NotNil(t, entry, "expected an auth failure log entry, got: %s", dumpEntries(hook))
	assert.Equal(t, http.StatusForbidden, entry.Data["http_status"])
	assert.Equal(t, int64(1), *requests, "permission failures must not be retried")
	assertNoSecretsLogged(t, hook)
}

// TestRecordsLogsTransientFailureAndRetries pins the fix for issue #19: a 503
// must be retried and every attempt must be logged with the status code.
func TestRecordsLogsTransientFailureAndRetries(t *testing.T) {
	hook := captureLogs(t)
	withInstantRetries(t)
	p, requests := newStubGrid(t, http.StatusServiceUnavailable, "503 Service Temporarily Unavailable")

	_, err := p.Records(context.TODO())
	require.Error(t, err)
	assert.Contains(t, err.Error(), "503")

	warned := findEntry(hook, log.WarnLevel, WAPIFailureTransient)
	require.NotNil(t, warned, "expected a warn-level retry log entry, got: %s", dumpEntries(hook))
	assert.Equal(t, http.StatusServiceUnavailable, warned.Data["http_status"])
	assert.Equal(t, "zone_auth", warned.Data["wapi_object"])

	exhausted := findEntry(hook, log.ErrorLevel, WAPIFailureTransient)
	require.NotNil(t, exhausted, "expected an error-level entry once retries are exhausted, got: %s", dumpEntries(hook))
	assert.Contains(t, exhausted.Message, "retries are exhausted")

	// Every attempt is sent twice, because the infoblox-go-client repeats a failed
	// request against the grid master. That repeat is only suppressed for auth
	// failures, since a transient failure can genuinely succeed on the retry.
	assert.Equal(t, int64(2*defaultGetAttempts), *requests, "transient failures must be retried")

	var warnCount int
	for _, entry := range hook.AllEntries() {
		if entry.Level == log.WarnLevel && entry.Data["failure_kind"] == string(WAPIFailureTransient) {
			warnCount++
		}
	}
	assert.Equal(t, defaultGetAttempts-1, warnCount, "every retried attempt must be logged")

	assertNoSecretsLogged(t, hook)
}

// TestApplyChangesLogsRejectedWrite is the direct reproduction of issue #50: a
// create that the grid refuses used to leave no log line at all.
func TestApplyChangesLogsRejectedWrite(t *testing.T) {
	hook := captureLogs(t)
	client := &mockIBConnector{
		mockInfobloxZones:   &[]ibclient.ZoneAuth{createMockInfobloxZone("example.com")},
		mockInfobloxObjects: &[]ibclient.IBObject{},
		createError:         errors.New("WAPI request error: 403('403 Forbidden')\nContents:\ninsufficient privileges\n"),
	}
	p := newInfobloxProvider(endpoint.NewDomainFilter([]string{"example.com"}),
		provider.NewZoneIDFilter([]string{""}), "", false, false, client)

	err := p.ApplyChanges(context.TODO(), &plan.Changes{
		Create: []*endpoint.Endpoint{
			endpoint.NewEndpoint("new.example.com", endpoint.RecordTypeCNAME, "target.example.com"),
		},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), strconv.Itoa(http.StatusForbidden))

	entry := findEntry(hook, log.ErrorLevel, WAPIFailureAuth)
	require.NotNil(t, entry, "expected a rejected write to be logged at error level, got: %s", dumpEntries(hook))
	assert.Equal(t, http.StatusForbidden, entry.Data["http_status"])
	assert.Equal(t, "record:cname", entry.Data["wapi_object"])
	assert.Equal(t, infobloxCreate, entry.Data["operation"])
	assertNoSecretsLogged(t, hook)
}

// TestChangesByZoneWarnsOnUnmatchedRecord covers the other half of issue #50:
// when the WAPI user cannot read the zones, every change is dropped, and that
// used to happen at debug level only.
func TestChangesByZoneWarnsOnUnmatchedRecord(t *testing.T) {
	hook := captureLogs(t)
	client := &mockIBConnector{}
	p := newInfobloxProvider(endpoint.NewDomainFilter([]string{"example.com"}),
		provider.NewZoneIDFilter([]string{""}), "", false, false, client)

	p.ChangesByZone(nil, []*infobloxChange{{
		Action:   infobloxCreate,
		Endpoint: endpoint.NewEndpoint("orphan.example.com", endpoint.RecordTypeA, "1.2.3.4"),
	}})

	var found bool
	for _, entry := range hook.AllEntries() {
		if entry.Level == log.WarnLevel && entry.Data["record"] == "orphan.example.com" {
			found = true
			assert.Equal(t, infobloxCreate, entry.Data["action"])
		}
	}
	assert.True(t, found, "expected a warning for the unmatched record, got: %s", dumpEntries(hook))
	assertNoSecretsLogged(t, hook)
}

func findEntry(hook *logtest.Hook, level log.Level, kind WAPIFailureKind) *log.Entry {
	for i, entry := range hook.AllEntries() {
		if entry.Level == level && entry.Data["failure_kind"] == string(kind) {
			return hook.AllEntries()[i]
		}
	}
	return nil
}

func dumpEntries(hook *logtest.Hook) string {
	var b strings.Builder
	for _, entry := range hook.AllEntries() {
		fmt.Fprintf(&b, "[%s] %s %v\n", entry.Level, entry.Message, entry.Data)
	}
	if b.Len() == 0 {
		return "<no log entries>"
	}
	return b.String()
}
