package infoblox

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"sync"
	"testing"

	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/plan"
)

// Fixtures shared by the WAPI wire tests.
const (
	wapiTestVersion  = "2.3.1"
	wapiTestFQDN     = "host.example.com"
	wapiTestIPv4     = "10.0.0.7"
	wapiTestZone     = "example.com"
	wapiTestRevZone  = "10.0.0.0/24"
	wapiTestArpaName = "7.0.0.10.in-addr.arpa"
)

// wapiFake is an in-process NIOS WAPI endpoint. Tests built on it drive the real
// infoblox-go-client stack (request builder, HTTP requestor, connector) so the
// assertions are about what goes on the wire: URL path, object type, query
// parameter names, request body field names, and response envelope shape.
//
// mockIBConnector in infoblox_test.go substitutes for ibclient.IBConnector and
// therefore cannot observe any of those. A record written to the wrong WAPI
// field, or looked up with the wrong query parameter name, is invisible to it.
type wapiFake struct {
	mu sync.Mutex

	// version is the WAPI version the fake accepts in the URL path.
	version string

	// zones is served for zone_auth reads.
	zones []map[string]any

	// records is the object store, keyed by _ref.
	records map[string]map[string]any
	nextID  int

	// requests records every request received, in order.
	requests []wapiRequest
}

// wapiRequest is one observed request, decomposed the way NIOS decomposes it.
type wapiRequest struct {
	Method     string
	Path       string
	Query      url.Values
	ObjectType string
	Ref        string
	Body       map[string]any
}

func newWAPIFake(version string) *wapiFake {
	return &wapiFake{
		version: version,
		records: map[string]map[string]any{},
	}
}

// addZone registers an authoritative zone. Reverse zones are given as CIDRs,
// matching how NIOS reports them.
func (f *wapiFake) addZone(fqdn string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.zones = append(f.zones, map[string]any{
		"_ref": fmt.Sprintf("zone_auth/%s:%s/default", strings.ReplaceAll(fqdn, "/", "-"), fqdn),
		"fqdn": fqdn,
		"view": "default",
	})
}

// addRecord seeds an object into the store and returns its ref.
func (f *wapiFake) addRecord(objectType string, fields map[string]any) string {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.storeLocked(objectType, fields)
}

func (f *wapiFake) storeLocked(objectType string, fields map[string]any) string {
	f.nextID++
	stored := map[string]any{}
	for k, v := range fields {
		stored[k] = v
	}
	// Refs are object-type prefixed, as NIOS emits them.
	ref := fmt.Sprintf("%s/fake-%d:%v/default", objectType, f.nextID, fields["name"])
	stored["_ref"] = ref
	f.records[ref] = stored
	return ref
}

func (f *wapiFake) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	objectType, ref, ok := f.parsePath(req.URL.Path)
	if !ok {
		http.Error(w, "path must be /wapi/v<version>/<object>[/<ref>]", http.StatusBadRequest)
		return
	}

	var body map[string]any
	if req.Body != nil {
		raw, _ := io.ReadAll(req.Body)
		if len(raw) > 0 {
			_ = json.Unmarshal(raw, &body)
		}
	}

	f.mu.Lock()
	f.requests = append(f.requests, wapiRequest{
		Method:     req.Method,
		Path:       req.URL.Path,
		Query:      req.URL.Query(),
		ObjectType: objectType,
		Ref:        ref,
		Body:       body,
	})
	f.mu.Unlock()

	switch req.Method {
	case http.MethodPost:
		f.mu.Lock()
		created := f.storeLocked(objectType, body)
		f.mu.Unlock()
		// NIOS answers a create with 201 and the bare ref string.
		f.writeJSON(w, http.StatusCreated, created)
	case http.MethodGet:
		f.serveGet(w, req, objectType)
	case http.MethodPut:
		if ref == "" {
			http.Error(w, "a ref is required", http.StatusBadRequest)
			return
		}
		f.mu.Lock()
		stored, found := f.records[ref]
		if found {
			for k, v := range body {
				stored[k] = v
			}
		}
		f.mu.Unlock()
		if !found {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		f.writeJSON(w, http.StatusOK, ref)
	case http.MethodDelete:
		if ref == "" {
			// A delete with no ref is what an empty lookup result produces. NIOS
			// rejects it; so must the fake, or the bug it represents is hidden.
			http.Error(w, "a ref is required", http.StatusBadRequest)
			return
		}
		f.mu.Lock()
		_, found := f.records[ref]
		delete(f.records, ref)
		f.mu.Unlock()
		if !found {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		f.writeJSON(w, http.StatusOK, ref)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

// parsePath splits /wapi/v<version>/<object>[/<ref>] the way NIOS does. A ref
// carries its own object-type prefix, so the object type is the first segment
// either way.
func (f *wapiFake) parsePath(path string) (objectType, ref string, ok bool) {
	trimmed := strings.Trim(path, "/")
	parts := strings.SplitN(trimmed, "/", 3)
	if len(parts) < 3 || parts[0] != "wapi" || parts[1] != "v"+f.version {
		return "", "", false
	}
	rest := parts[2]
	segments := strings.SplitN(rest, "/", 2)
	objectType = strings.ToLower(segments[0])
	if len(segments) > 1 {
		ref = rest
	}
	return objectType, ref, true
}

func (f *wapiFake) serveGet(w http.ResponseWriter, req *http.Request, objectType string) {
	var result []map[string]any
	if objectType == "zone_auth" {
		f.mu.Lock()
		result = append(result, f.zones...)
		f.mu.Unlock()
	} else {
		result = f.find(objectType, req.URL.Query())
	}
	if result == nil {
		result = []map[string]any{}
	}
	// _return_as_object=1 wraps the result set; without it NIOS returns a bare
	// array. The webhook uses both shapes, so the fake must honour the flag.
	if req.URL.Query().Get("_return_as_object") == "1" {
		f.writeJSON(w, http.StatusOK, map[string]any{"result": result})
		return
	}
	f.writeJSON(w, http.StatusOK, result)
}

// wapiSearchFields are the object fields NIOS accepts as search criteria for the
// DNS record types this webhook manages. A query naming a field outside this set
// still filters on it here, which is what makes a wrong parameter name visible:
// the search simply matches nothing.
var wapiSearchFields = []string{
	"name", "view", "zone",
	"ipv4addr", "ipv6addr",
	"ptrdname", "canonical", "text", "nameserver",
}

func (f *wapiFake) find(objectType string, query url.Values) []map[string]any {
	f.mu.Lock()
	defer f.mu.Unlock()

	var result []map[string]any
	for ref, stored := range f.records {
		if !strings.HasPrefix(ref, objectType+"/") {
			continue
		}
		matched := true
		for _, field := range wapiSearchFields {
			want := query.Get(field)
			if want == "" {
				continue
			}
			got, _ := stored[field].(string)
			if got != want {
				matched = false
				break
			}
		}
		if !matched {
			continue
		}
		copied := map[string]any{}
		for k, v := range stored {
			copied[k] = v
		}
		result = append(result, copied)
	}
	return result
}

func (f *wapiFake) writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}

// observed returns the requests received so far.
func (f *wapiFake) observed() []wapiRequest {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]wapiRequest, len(f.requests))
	copy(out, f.requests)
	return out
}

// stored reports whether a ref is still present.
func (f *wapiFake) stored(ref string) bool {
	f.mu.Lock()
	defer f.mu.Unlock()
	_, ok := f.records[ref]
	return ok
}

// firstRequest returns the first observed request matching a method and object
// type.
func (f *wapiFake) firstRequest(t *testing.T, method, objectType string) wapiRequest {
	t.Helper()
	for _, req := range f.observed() {
		if req.Method == method && req.ObjectType == objectType {
			return req
		}
	}
	t.Fatalf("no %s request for object type %q; observed %s", method, objectType, f.summary())
	return wapiRequest{}
}

func (f *wapiFake) summary() string {
	var parts []string
	for _, req := range f.observed() {
		parts = append(parts, fmt.Sprintf("%s %s?%s", req.Method, req.Path, req.Query.Encode()))
	}
	return strings.Join(parts, "; ")
}

// startWAPIFake serves the fake over TLS and returns a Provider built through
// NewInfobloxProvider, so the connector under test is the production one.
func startWAPIFake(t *testing.T, domainFilter *endpoint.DomainFilter) (*Provider, *wapiFake) {
	t.Helper()

	fake := newWAPIFake(wapiTestVersion)
	server := httptest.NewTLSServer(fake)
	t.Cleanup(server.Close)

	endpointURL, err := url.Parse(server.URL)
	if err != nil {
		t.Fatalf("parse fake server URL: %v", err)
	}
	host, port := endpointURL.Hostname(), endpointURL.Port()
	portNumber := 0
	if _, err := fmt.Sscanf(port, "%d", &portNumber); err != nil {
		t.Fatalf("parse fake server port %q: %v", port, err)
	}

	providerCfg, err := NewInfobloxProvider(&StartupConfig{
		Host:         host,
		Port:         portNumber,
		Username:     "wapi-user",
		Password:     "wapi-password",
		Version:      wapiTestVersion,
		SSLVerify:    false,
		View:         "default",
		MaxResults:   1000,
		CreatePTR:    true,
		DefaultTTL:   300,
		UseTTL:       true,
		ExtAttrsJSON: "{}",
	}, domainFilter)
	if err != nil {
		t.Fatalf("NewInfobloxProvider: %v", err)
	}
	return providerCfg, fake
}

// TestWAPICreateAddressFamilyFields asserts the WAPI field names and object
// types a create puts on the wire for both an A record and its PTR companion.
//
// This is the assertion mockIBConnector structurally cannot make. It reads
// whichever address field the provider happens to have populated on the
// ibclient struct, so a record written to the wrong address-family field looks
// identical to a correct one. A grid does not: ipv4addr and ipv6addr are
// distinct fields on record:ptr and only one of them is the address.
func TestWAPICreateAddressFamilyFields(t *testing.T) {
	providerCfg, fake := startWAPIFake(t, endpoint.NewDomainFilter([]string{wapiTestZone, wapiTestRevZone}))
	fake.addZone(wapiTestZone)
	fake.addZone(wapiTestRevZone)

	err := providerCfg.ApplyChanges(context.Background(), &plan.Changes{
		Create: []*endpoint.Endpoint{
			endpoint.NewEndpoint(wapiTestFQDN, endpoint.RecordTypeA, wapiTestIPv4),
		},
	})
	if err != nil {
		t.Fatalf("ApplyChanges: %v", err)
	}

	aCreate := fake.firstRequest(t, http.MethodPost, recordA)
	if got, _ := aCreate.Body["ipv4addr"].(string); got != wapiTestIPv4 {
		t.Errorf("record:a body ipv4addr = %q, want %q", got, wapiTestIPv4)
	}
	if _, present := aCreate.Body["ipv6addr"]; present {
		t.Error("record:a body carries ipv6addr; an IPv4 address must not be written to the IPv6 field")
	}
	if got, _ := aCreate.Body["name"].(string); got != wapiTestFQDN {
		t.Errorf("record:a body name = %q, want %q", got, wapiTestFQDN)
	}

	ptrCreate := fake.firstRequest(t, http.MethodPost, recordPtr)
	if got, _ := ptrCreate.Body["ipv4addr"].(string); got != wapiTestIPv4 {
		t.Errorf("record:ptr body ipv4addr = %q, want %q", got, wapiTestIPv4)
	}
	if _, present := ptrCreate.Body["ipv6addr"]; present {
		t.Error("record:ptr body carries ipv6addr; an IPv4 PTR target must not be written to the IPv6 field")
	}
	if got, _ := ptrCreate.Body["ptrdname"].(string); got != wapiTestFQDN {
		t.Errorf("record:ptr body ptrdname = %q, want %q", got, wapiTestFQDN)
	}
}

// TestWAPIDeleteLookupQueryParams asserts the query parameter names a delete
// uses to resolve a record's ref, and that the delete reaches the object.
//
// A wrong parameter name is silent in mockIBConnector, which matches PTR reads
// on the ibclient struct rather than on the query string. Over HTTP it is not
// silent: the search matches nothing, the ref stays empty and the delete fails.
func TestWAPIDeleteLookupQueryParams(t *testing.T) {
	providerCfg, fake := startWAPIFake(t, endpoint.NewDomainFilter([]string{wapiTestZone, wapiTestRevZone}))
	fake.addZone(wapiTestZone)
	fake.addZone(wapiTestRevZone)

	aRef := fake.addRecord(recordA, map[string]any{
		"name":     wapiTestFQDN,
		"ipv4addr": wapiTestIPv4,
		"view":     "default",
	})
	ptrRef := fake.addRecord(recordPtr, map[string]any{
		"name":     wapiTestArpaName,
		"ptrdname": wapiTestFQDN,
		"ipv4addr": wapiTestIPv4,
		"view":     "default",
	})

	err := providerCfg.ApplyChanges(context.Background(), &plan.Changes{
		Delete: []*endpoint.Endpoint{
			endpoint.NewEndpoint(wapiTestFQDN, endpoint.RecordTypeA, wapiTestIPv4),
		},
	})
	if err != nil {
		t.Fatalf("ApplyChanges: %v", err)
	}

	aLookup := fake.firstRequest(t, http.MethodGet, recordA)
	if got := aLookup.Query.Get("ipv4addr"); got != wapiTestIPv4 {
		t.Errorf("record:a lookup ipv4addr = %q, want %q (query was %q)", got, wapiTestIPv4, aLookup.Query.Encode())
	}
	if got := aLookup.Query.Get("name"); got != wapiTestFQDN {
		t.Errorf("record:a lookup name = %q, want %q", got, wapiTestFQDN)
	}

	ptrLookup := fake.firstRequest(t, http.MethodGet, recordPtr)
	if got := ptrLookup.Query.Get("ipv4addr"); got != wapiTestIPv4 {
		t.Errorf("record:ptr lookup ipv4addr = %q, want %q (query was %q)", got, wapiTestIPv4, ptrLookup.Query.Encode())
	}
	if got := ptrLookup.Query.Get("ptrdname"); got != wapiTestFQDN {
		t.Errorf("record:ptr lookup ptrdname = %q, want %q", got, wapiTestFQDN)
	}

	// The lookup resolved a real ref, so the delete removed a real object.
	if fake.stored(aRef) {
		t.Error("record:a survived the delete; the lookup did not resolve its ref")
	}
	if fake.stored(ptrRef) {
		t.Error("record:ptr survived the delete; the lookup did not resolve its ref")
	}
}

// TestWAPIReadResponseEnvelope asserts the webhook parses the paged response
// envelope NIOS returns for _return_as_object=1 reads, and that a read reaches
// both the forward and the reverse zone.
//
// mockIBConnector fills the response struct directly, so it cannot catch an
// envelope the client fails to unmarshal.
func TestWAPIReadResponseEnvelope(t *testing.T) {
	providerCfg, fake := startWAPIFake(t, endpoint.NewDomainFilter([]string{wapiTestZone, wapiTestRevZone}))
	fake.addZone(wapiTestZone)
	fake.addZone(wapiTestRevZone)

	fake.addRecord(recordA, map[string]any{
		"name":     wapiTestFQDN,
		"ipv4addr": wapiTestIPv4,
		"view":     "default",
		"zone":     wapiTestZone,
	})
	fake.addRecord(recordPtr, map[string]any{
		"name":     wapiTestArpaName,
		"ptrdname": wapiTestFQDN,
		"ipv4addr": wapiTestIPv4,
		"view":     "default",
		"zone":     "0.0.10.in-addr.arpa",
	})

	endpoints, err := providerCfg.Records(context.Background())
	if err != nil {
		t.Fatalf("Records: %v", err)
	}

	var sawA, sawPTR bool
	for _, ep := range endpoints {
		switch ep.RecordType {
		case endpoint.RecordTypeA:
			sawA = true
			if len(ep.Targets) != 1 || ep.Targets[0] != wapiTestIPv4 {
				t.Errorf("A endpoint targets = %v, want [10.0.0.7]", ep.Targets)
			}
		case endpoint.RecordTypePTR:
			sawPTR = true
			if len(ep.Targets) != 1 || ep.Targets[0] != wapiTestIPv4 {
				t.Errorf("PTR endpoint targets = %v, want [10.0.0.7]", ep.Targets)
			}
			if ep.DNSName != wapiTestFQDN {
				t.Errorf("PTR endpoint DNSName = %q, want %q", ep.DNSName, wapiTestFQDN)
			}
		}
	}
	if !sawA {
		t.Error("no A endpoint was read back from the fake grid")
	}
	if !sawPTR {
		t.Error("no PTR endpoint was read back from the fake grid")
	}

	// The reverse read must address the in-addr.arpa zone, not the CIDR that
	// zone_auth reports.
	var sawArpaRead bool
	for _, req := range fake.observed() {
		if req.Method == http.MethodGet && req.ObjectType == recordPtr &&
			strings.HasSuffix(req.Query.Get("zone"), ".in-addr.arpa") {
			sawArpaRead = true
		}
	}
	if !sawArpaRead {
		t.Errorf("no record:ptr read named an in-addr.arpa zone; observed %s", fake.summary())
	}
}

// TestWAPIRequestShape asserts the URL shape and HTTP methods the webhook uses,
// across a read and a write. A drifted path or an unexpected method is rejected
// by a grid before it reaches any record.
func TestWAPIRequestShape(t *testing.T) {
	providerCfg, fake := startWAPIFake(t, endpoint.NewDomainFilter([]string{wapiTestZone, wapiTestRevZone}))
	fake.addZone(wapiTestZone)
	fake.addZone(wapiTestRevZone)

	if _, err := providerCfg.Records(context.Background()); err != nil {
		t.Fatalf("Records: %v", err)
	}
	err := providerCfg.ApplyChanges(context.Background(), &plan.Changes{
		Create: []*endpoint.Endpoint{
			endpoint.NewEndpoint("shape.example.com", endpoint.RecordTypeA, "10.0.0.9"),
		},
	})
	if err != nil {
		t.Fatalf("ApplyChanges: %v", err)
	}

	allowedObjects := map[string]bool{
		"zone_auth": true,
		recordA:     true,
		recordPtr:   true,
		recordCname: true,
		recordNs:    true,
		recordTxt:   true,
		recordHost:  true,
	}
	allowedMethods := map[string]bool{
		http.MethodGet: true, http.MethodPost: true,
		http.MethodPut: true, http.MethodDelete: true,
	}

	observed := fake.observed()
	if len(observed) == 0 {
		t.Fatal("no requests reached the fake grid")
	}
	for _, req := range observed {
		if !strings.HasPrefix(req.Path, "/wapi/v"+wapiTestVersion+"/") {
			t.Errorf("path %q is not /wapi/v<version>/<object>", req.Path)
		}
		if !allowedObjects[req.ObjectType] {
			t.Errorf("request %s %s used unexpected object type %q", req.Method, req.Path, req.ObjectType)
		}
		if !allowedMethods[req.Method] {
			t.Errorf("request %s %s used unexpected method", req.Method, req.Path)
		}
	}
}

// TestWAPIFakeRejectsRefLessDelete proves the fake enforces the constraint the
// delete tests rely on, so a passing delete assertion means something.
func TestWAPIFakeRejectsRefLessDelete(t *testing.T) {
	fake := newWAPIFake(wapiTestVersion)
	server := httptest.NewTLSServer(fake)
	defer server.Close()

	req, err := http.NewRequestWithContext(context.Background(), http.MethodDelete, server.URL+"/wapi/v"+wapiTestVersion+"/"+recordA, nil)
	if err != nil {
		t.Fatalf("build request: %v", err)
	}
	resp, err := server.Client().Do(req)
	if err != nil {
		t.Fatalf("send request: %v", err)
	}
	t.Cleanup(func() {
		if err := resp.Body.Close(); err != nil {
			t.Errorf("close response body: %v", err)
		}
	})
	if resp.StatusCode != http.StatusBadRequest {
		t.Errorf("status = %d, want 400 for a delete with no ref", resp.StatusCode)
	}
}
