package infoblox

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"errors"
	"io"
	"net"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"sync"

	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	log "github.com/sirupsen/logrus"
)

// WAPIFailureKind classifies why a WAPI call failed. The distinction matters
// because transient failures are worth retrying while authentication and
// authorization failures are not: retrying them only hides the misconfiguration
// and can lock out the WAPI account.
type WAPIFailureKind string

const (
	// WAPIFailureAuth covers 401 (bad credentials) and 403 (insufficient
	// permissions for the WAPI user). Never retried.
	WAPIFailureAuth WAPIFailureKind = "auth"
	// WAPIFailureTransient covers 429/502/503/504, connection resets, EOFs and
	// timeouts. Safe to retry.
	WAPIFailureTransient WAPIFailureKind = "transient"
	// WAPIFailureNotFound is the expected "object does not exist" answer.
	WAPIFailureNotFound WAPIFailureKind = "not_found"
	// WAPIFailureOther is any other error, e.g. a malformed request. Not retried.
	WAPIFailureOther WAPIFailureKind = "other"
)

// statusFromWapiMessage extracts the HTTP status code out of the message the
// infoblox-go-client builds in getHTTPResponseError, which has the shape
// "WAPI request error: 503('503 Service Temporarily Unavailable')".
var statusFromWapiMessage = regexp.MustCompile(`WAPI request error: (\d{3})`)

// urlUserInfo matches the "user:password@" part of a URL so it can be stripped
// before anything derived from an error is written to the log.
var urlUserInfo = regexp.MustCompile(`(?i)(https?://)[^/\s"']*@`)

// collapseWhitespace is used to keep a log field on a single line. The
// infoblox-go-client embeds the raw response body, including newlines.
var collapseWhitespace = regexp.MustCompile(`\s+`)

// reasonMaxLen bounds the length of the reason log field so that a large HTML
// error page from a load balancer cannot flood the log.
const reasonMaxLen = 512

// WAPIFailure is the classification of a failed WAPI call.
type WAPIFailure struct {
	// Kind is the coarse category used to decide whether to retry.
	Kind WAPIFailureKind
	// StatusCode is the HTTP status code, or 0 when the request never got a
	// response (connection error, timeout).
	StatusCode int
}

// Retryable reports whether the call may be repeated. Authentication and
// authorization failures are deliberately not retryable.
func (f WAPIFailure) Retryable() bool {
	return f.Kind == WAPIFailureTransient
}

// ClassifyWAPIError maps an error returned by the infoblox-go-client onto a
// WAPIFailure. It never returns a nil-safe zero value for a nil error; callers
// must only call it with a non-nil error.
func ClassifyWAPIError(err error) WAPIFailure {
	var notFound *ibclient.NotFoundError
	if errors.As(err, &notFound) {
		return WAPIFailure{Kind: WAPIFailureNotFound, StatusCode: http.StatusNotFound}
	}

	if m := statusFromWapiMessage.FindStringSubmatch(err.Error()); m != nil {
		status, convErr := strconv.Atoi(m[1])
		if convErr == nil {
			return WAPIFailure{Kind: kindForStatus(status), StatusCode: status}
		}
	}

	if isTransientTransportError(err) {
		return WAPIFailure{Kind: WAPIFailureTransient}
	}

	return WAPIFailure{Kind: WAPIFailureOther}
}

func kindForStatus(status int) WAPIFailureKind {
	switch status {
	case http.StatusUnauthorized, http.StatusForbidden:
		return WAPIFailureAuth
	case http.StatusNotFound:
		return WAPIFailureNotFound
	case http.StatusTooManyRequests,
		http.StatusBadGateway,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		return WAPIFailureTransient
	default:
		return WAPIFailureOther
	}
}

// isTransientTransportError detects failures that happened below the HTTP status
// layer: timeouts, resets and truncated responses. Issue #19 reports Infoblox
// grids answering with a bare EOF once the request is redirected to the grid
// master, which surfaces here.
func isTransientTransportError(err error) bool {
	if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
		return true
	}
	var netErr net.Error
	if errors.As(err, &netErr) && netErr.Timeout() {
		return true
	}
	var opErr *net.OpError
	if errors.As(err, &opErr) {
		return true
	}
	msg := err.Error()
	for _, needle := range []string{
		"context deadline exceeded",
		"connection refused",
		"connection reset by peer",
		"i/o timeout",
		"EOF",
		"TLS handshake timeout",
		"no such host",
	} {
		if strings.Contains(msg, needle) {
			return true
		}
	}
	return false
}

// AuthAwareRequestor decorates an ibclient.HttpRequestor.
//
// The infoblox-go-client transparently repeats every failed request with
// _proxy_search=GM appended, to redirect it to the grid master (see
// Connector.makeRequest). That doubles the request count for a failure the
// retry can never fix: if the WAPI user is not authenticated or not authorized,
// the grid master rejects it too, and the extra attempt only brings the account
// closer to a lockout. This decorator remembers the last authentication or
// authorization failure per method and path and answers the grid-master repeat
// of that same request from memory instead of sending it.
//
// Issue #19 traces the 503s and EOFs to that same grid-master redirect, so the
// redirect is logged at debug level to make it visible.
type AuthAwareRequestor struct {
	inner ibclient.HttpRequestor

	mu           sync.Mutex
	authFailures map[string]error
}

// NewAuthAwareRequestor wraps requestor. A nil requestor yields a plain
// ibclient.WapiHttpRequestor.
func NewAuthAwareRequestor(requestor ibclient.HttpRequestor) *AuthAwareRequestor {
	if requestor == nil {
		requestor = &ibclient.WapiHttpRequestor{}
	}
	return &AuthAwareRequestor{inner: requestor, authFailures: map[string]error{}}
}

func (r *AuthAwareRequestor) Init(authCfg ibclient.AuthConfig, trCfg ibclient.TransportConfig) {
	r.inner.Init(authCfg, trCfg)
}

func (r *AuthAwareRequestor) SendRequest(req *http.Request) ([]byte, error) {
	key := req.Method + " " + req.URL.Path
	isProxyRetry := req.URL.Query().Get("_proxy_search") == "GM"

	if isProxyRetry {
		r.mu.Lock()
		previous, blocked := r.authFailures[key]
		r.mu.Unlock()
		if blocked {
			log.WithFields(log.Fields{
				"wapi_path":   req.URL.Path,
				"http_method": req.Method,
			}).Debug("Not repeating the request against the Infoblox grid master: the previous attempt failed authentication or authorization and repeating it cannot succeed")
			return nil, previous
		}
		log.WithFields(log.Fields{
			"wapi_path":   req.URL.Path,
			"http_method": req.Method,
		}).Debug("Repeating the Infoblox WAPI request against the grid master (_proxy_search=GM)")
	}

	res, err := r.inner.SendRequest(req)

	r.mu.Lock()
	if err != nil && ClassifyWAPIError(err).Kind == WAPIFailureAuth {
		r.authFailures[key] = err
	} else {
		delete(r.authFailures, key)
	}
	r.mu.Unlock()

	return res, err
}

// SanitizeWAPIReason turns an error into a single-line, length-bounded log
// value with any URL credentials removed. Only the reason reported by the grid
// is kept; request bodies and credentials are never part of the output.
func SanitizeWAPIReason(err error) string {
	if err == nil {
		return ""
	}
	reason := urlUserInfo.ReplaceAllString(err.Error(), "$1")
	reason = collapseWhitespace.ReplaceAllString(reason, " ")
	reason = strings.TrimSpace(reason)
	if len(reason) > reasonMaxLen {
		reason = reason[:reasonMaxLen] + "..."
	}
	return reason
}

// logWAPIFailure emits a single structured line for a failed WAPI call. It
// records the HTTP status code, the WAPI object type that was addressed and the
// sanitized reason. It deliberately never logs credentials, the WAPI user or a
// request body.
func logWAPIFailure(objectType, operation string, failure WAPIFailure, attempt, attempts int, err error) {
	fields := log.Fields{
		"wapi_object":  objectType,
		"operation":    operation,
		"http_status":  failure.StatusCode,
		"failure_kind": string(failure.Kind),
		"reason":       SanitizeWAPIReason(err),
	}
	if attempts > 1 {
		fields["attempt"] = attempt
		fields["max_attempts"] = attempts
	}

	entry := log.WithFields(fields)
	switch failure.Kind {
	case WAPIFailureAuth:
		entry.Error("Infoblox WAPI rejected the request: the configured WAPI user is not authenticated or lacks permissions for this object type. Verify the credentials and the permissions granted to INFOBLOX_WAPI_USER; this request will not be retried")
	case WAPIFailureTransient:
		if attempt < attempts {
			entry.Warn("Infoblox WAPI call failed with a transient error, retrying")
			return
		}
		entry.Error("Infoblox WAPI call failed with a transient error and all retries are exhausted")
	case WAPIFailureNotFound:
		entry.Debug("Infoblox WAPI reported the requested object does not exist")
	default:
		entry.Error("Infoblox WAPI call failed")
	}
}
