package dnsprovider

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/AbsaOSS/external-dns-infoblox-webhook/cmd/webhook/init/configuration"
	"github.com/AbsaOSS/external-dns-infoblox-webhook/internal/infoblox"

	"github.com/alecthomas/kong"
	log "github.com/sirupsen/logrus"
	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/provider"
)

// nolint: revive
func Init(config configuration.Config) (provider.Provider, error) {
	var domainFilter endpoint.DomainFilter
	createMsg := "Creating infoblox provider with "

	if config.RegexDomainFilter != "" {
		createMsg += fmt.Sprintf("regexp domain filter: '%s', ", config.RegexDomainFilter)
		if config.RegexDomainExclusion != "" {
			createMsg += fmt.Sprintf("with exclusion: '%s', ", config.RegexDomainExclusion)
		}
		domainFilter = endpoint.NewRegexDomainFilter(
			regexp.MustCompile(config.RegexDomainFilter),
			regexp.MustCompile(config.RegexDomainExclusion),
		)
	} else {
		if len(config.DomainFilter) > 0 {
			createMsg += fmt.Sprintf("domain filter: '%s', ", strings.Join(config.DomainFilter, ","))
		}
		if len(config.ExcludeDomains) > 0 {
			createMsg += fmt.Sprintf("exclude domain filter: '%s', ", strings.Join(config.ExcludeDomains, ","))
		}
		domainFilter = endpoint.NewDomainFilterWithExclusions(config.DomainFilter, config.ExcludeDomains)
	}

	createMsg = strings.TrimSuffix(createMsg, ", ")
	if strings.HasSuffix(createMsg, "with ") {
		createMsg += "no kind of domain filters"
	}
	log.Info(createMsg)

	infobloxConfig, err := getInfobloxStartupConfig()
	if err != nil {
		return nil, err
	}
	infobloxConfig.FQDNRegEx = config.RegexDomainFilter
	infobloxConfig.NameRegEx = config.RegexNameFilter

	return infoblox.NewInfobloxProvider(infobloxConfig, domainFilter)
}

func getInfobloxStartupConfig() (*infoblox.StartupConfig, error) {
	infobloxConfig := &infoblox.StartupConfig{}
	parser, err := kong.New(infobloxConfig)
	if err != nil {
		return nil, fmt.Errorf("error reading configuration from environment: %v", err)
	}
	_, err = parser.Parse([]string{})
	if err != nil {
		return nil, fmt.Errorf("error parsing configuration from environment: %v", err)
	}
	return infobloxConfig, nil
}
