package configuration

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"time"

	"github.com/alecthomas/kong"
	log "github.com/sirupsen/logrus"
)

// Config struct for configuration environmental variables
type Config struct {
	ServerHost           string        `env:"SERVER_HOST" validate:"required" default:"127.0.0.1"`
	ServerPort           int           `env:"SERVER_PORT" validate:"required" default:"8888"`
	HealthCheckPort      int           `env:"HEALTH_CHECK_PORT" validate:"required" default:"8080"`
	ServerReadTimeout    time.Duration `env:"SERVER_READ_TIMEOUT"`
	ServerWriteTimeout   time.Duration `env:"SERVER_WRITE_TIMEOUT"`
	DomainFilter         []string      `env:"DOMAIN_FILTER" default:""`
	ExcludeDomains       []string      `env:"EXCLUDE_DOMAIN_FILTER" default:""`
	RegexDomainFilter    string        `env:"REGEXP_DOMAIN_FILTER" default:""`
	RegexDomainExclusion string        `env:"REGEXP_DOMAIN_FILTER_EXCLUSION" default:""`
	RegexNameFilter      string        `env:"REGEXP_NAME_FILTER" default:""`
}

// Init sets up configuration by reading set environmental variables
func Init() Config {
	cfg := &Config{}
	parser, err := kong.New(cfg)
	if err != nil {
		log.Fatalf("Error reading configuration from environment: %v", err)
	}
	_, err = parser.Parse([]string{})
	if err != nil {
		log.Fatalf("Error parsing configuration from environment: %v", err)
	}
	return *cfg
}
